server:
  port: 8888

# logging
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

# JPA
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  http:
    multipart:
      location: "C:\\SKY\\tmp"
